name:                chess-maine-event-scraper-haskell
version:             0.1.0.0
github:              "githubuser/chess-maine-event-scraper-haskell"
license:             BSD-3-Clause
author:              "Jeff Merckens"
maintainer:          "me@jeffmerckens.com"
copyright:           "2025 Jeff Merckens"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Merckinator/chess-maine-event-scraper-haskell#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  chess-maine-event-scraper-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-maine-event-scraper-haskell
    - bytestring
    - http-conduit
    - http-client-tls
    - tagsoup
    - text

tests:
  chess-maine-event-scraper-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chess-maine-event-scraper-haskell
